name: Unit Testing

on:
  pull_request:
    branches:
      - master
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          ZEEGUU_RESOURCES_FOLDER=`pwd`
          echo $ZEEGUU_RESOURCES_FOLDER
          python setup.py develop
          python install_stanza_models.py
      - name: Test with pytest
        run: |
          pytest
